# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.5.0'
  azureServiceConnection: 'Terraform-Connection-AZ305'

steps:
  - script: |
      echo "Installing Terraform..."
      sudo apt-get update && sudo apt-get install -y unzip
      curl -fsSL https://releases.hashicorp.com/terraform/$(terraformVersion)/terraform_$(terraformVersion)_linux_amd64.zip -o terraform.zip
      unzip terraform.zip
      sudo mv terraform /usr/local/bin/
      terraform --version
    displayName: 'Install Terraform'

  - checkout: self  

  - script: |
      echo "Initializing Terraform..."
      terraform init

      echo "Running Terraform Plan..."
      terraform plan \
        -var "admin_password=$(admin_password)"\
      -var "admin_username=$(admin_username)" 
    displayName: 'Terraform Init & Plan'

  - script: |
      echo "Applying Terraform..."
      terraform apply -auto-approve \
        -var "admin_password=$(admin_password)"\
      -var "admin_username=$(admin_username)" 
    displayName: 'Terraform Apply'

